export { default as Welcome } from "./Welcome";
export { default as Signup } from "./Signup";
export { default as Login } from "./Login";
export { default as Profile } from "./Profile";
export { default as Home } from "./Home";
export { default as Collections } from "./Collections";
export { default as Categories } from "./Categories";
export { default as Post } from "./Post";
export { default as CreateCollection } from "./CreateCollection";
